#!/bin/bash

## Releases will be created under the latest tag pushed, or Travis
## will create a name for the tag automatically if there is none.
## The tag name is part of the download URL, naming and pushing a 
## tag keeps the download URL predictable and easier to update.

readonly REPO_URL="https://${BOT_AUTH_TOKEN}@github.com/triplea-game/assets.git"
git config --global user.email "tripleabuilderbot@gmail.com"
git config --global user.name "tripleabuilderbot"

## Add a '2' prefix to increment the build number.
## The build numbers are out of order, the '2' will ensure
## the latest tag is actually the latest build

RELEASE_NUMBER="1$TRAVIS_BUILD_NUMBER"
git tag "2$RELEASE_NUMBER" -a -f -m "2$RELEASE_NUMBER"
git push -q "$REPO_URL" --tags

